services:
  api:
    build: 
      context: .          
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file: 
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3





